<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RestSharp" Version="107.3.0" />
    <PackageReference Include="HtmlAgilityPack" Version="1.11.56" />
    <PackageReference Include="CsvHelper" Version="30.0.0" />
    <PackageReference Include="EPPlus" Version="7.0.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BDBlio.Core\BDBlio.Core.csproj" />
    <ProjectReference Include="..\BDBlio.Data\BDBlio.Data.csproj" />
  </ItemGroup>

</Project>
